// <auto-generated />
using System;
using Assignment02.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment02.Migrations
{
    [DbContext(typeof(ITIDBContext))]
    [Migration("20250323010743_After Mapping")]
    partial class AfterMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment02.Entites.CoursIns", b =>
                {
                    b.Property<int>("Ins_Id")
                        .HasColumnType("int");

                    b.Property<int>("Course_ID")
                        .HasColumnType("int");

                    b.Property<int>("evaluation")
                        .HasColumnType("int");

                    b.HasKey("Ins_Id", "Course_ID");

                    b.ToTable("CoursIns");
                });

            modelBuilder.Entity("Assignment02.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Description")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Top_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Top_ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Assignment02.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date");

                    b.Property<int?>("Ins_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ins_Id")
                        .IsUnique()
                        .HasFilter("[Ins_Id] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Assignment02.Entites.Instrucotr", b =>
                {
                    b.Property<int>("Ins_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ins_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bouns")
                        .HasColumnType("int");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<int>("HourRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ins_Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Instrucotrs");
                });

            modelBuilder.Entity("Assignment02.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Assignment02.Entites.StudentCourse", b =>
                {
                    b.Property<int>("St_ID")
                        .HasColumnType("int");

                    b.Property<int>("Couse_ID")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("St_ID", "Couse_ID");

                    b.HasIndex("Couse_ID");

                    b.ToTable("studentCourses");
                });

            modelBuilder.Entity("Assignment02.Entites.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Course_ID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("CoursInsCourse", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("CoursInsIns_Id")
                        .HasColumnType("int");

                    b.Property<int>("CoursInsCourse_ID")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "CoursInsIns_Id", "CoursInsCourse_ID");

                    b.HasIndex("CoursInsIns_Id", "CoursInsCourse_ID");

                    b.ToTable("CoursInsCourse");
                });

            modelBuilder.Entity("CoursInsInstrucotr", b =>
                {
                    b.Property<int>("InstrucotrsIns_Id")
                        .HasColumnType("int");

                    b.Property<int>("CoursInsIns_Id")
                        .HasColumnType("int");

                    b.Property<int>("CoursInsCourse_ID")
                        .HasColumnType("int");

                    b.HasKey("InstrucotrsIns_Id", "CoursInsIns_Id", "CoursInsCourse_ID");

                    b.HasIndex("CoursInsIns_Id", "CoursInsCourse_ID");

                    b.ToTable("CoursInsInstrucotr");
                });

            modelBuilder.Entity("Assignment02.Entites.Course", b =>
                {
                    b.HasOne("Assignment02.Entites.Topic", "Topic")
                        .WithMany("courses")
                        .HasForeignKey("Top_ID");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Assignment02.Entites.Department", b =>
                {
                    b.HasOne("Assignment02.Entites.Instrucotr", "Manager")
                        .WithOne("Manage")
                        .HasForeignKey("Assignment02.Entites.Department", "Ins_Id");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Assignment02.Entites.Instrucotr", b =>
                {
                    b.HasOne("Assignment02.Entites.Department", "Department")
                        .WithMany("instrucotrs")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Assignment02.Entites.Student", b =>
                {
                    b.HasOne("Assignment02.Entites.Department", "Department")
                        .WithMany("students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Assignment02.Entites.StudentCourse", b =>
                {
                    b.HasOne("Assignment02.Entites.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("Couse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment02.Entites.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("St_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoursInsCourse", b =>
                {
                    b.HasOne("Assignment02.Entites.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment02.Entites.CoursIns", null)
                        .WithMany()
                        .HasForeignKey("CoursInsIns_Id", "CoursInsCourse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoursInsInstrucotr", b =>
                {
                    b.HasOne("Assignment02.Entites.Instrucotr", null)
                        .WithMany()
                        .HasForeignKey("InstrucotrsIns_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment02.Entites.CoursIns", null)
                        .WithMany()
                        .HasForeignKey("CoursInsIns_Id", "CoursInsCourse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment02.Entites.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Assignment02.Entites.Department", b =>
                {
                    b.Navigation("instrucotrs");

                    b.Navigation("students");
                });

            modelBuilder.Entity("Assignment02.Entites.Instrucotr", b =>
                {
                    b.Navigation("Manage")
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment02.Entites.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Assignment02.Entites.Topic", b =>
                {
                    b.Navigation("courses");
                });
#pragma warning restore 612, 618
        }
    }
}
